/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as PrivacyLegalRouteImport } from './routes/privacy-legal'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminSecretPortalRouteImport } from './routes/admin-secret-portal'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaskMovieIdRouteImport } from './routes/task.$movieId'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyLegalRoute = PrivacyLegalRouteImport.update({
  id: '/privacy-legal',
  path: '/privacy-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecretPortalRoute = AdminSecretPortalRouteImport.update({
  id: '/admin-secret-portal',
  path: '/admin-secret-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskMovieIdRoute = TaskMovieIdRouteImport.update({
  id: '/task/$movieId',
  path: '/task/$movieId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-secret-portal': typeof AdminSecretPortalRoute
  '/auth': typeof AuthRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dashboard': typeof DashboardRoute
  '/privacy-legal': typeof PrivacyLegalRoute
  '/tasks': typeof TasksRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/wallet': typeof WalletRoute
  '/task/$movieId': typeof TaskMovieIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-secret-portal': typeof AdminSecretPortalRoute
  '/auth': typeof AuthRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dashboard': typeof DashboardRoute
  '/privacy-legal': typeof PrivacyLegalRoute
  '/tasks': typeof TasksRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/wallet': typeof WalletRoute
  '/task/$movieId': typeof TaskMovieIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-secret-portal': typeof AdminSecretPortalRoute
  '/auth': typeof AuthRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/dashboard': typeof DashboardRoute
  '/privacy-legal': typeof PrivacyLegalRoute
  '/tasks': typeof TasksRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/wallet': typeof WalletRoute
  '/task/$movieId': typeof TaskMovieIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/account'
    | '/admin'
    | '/admin-secret-portal'
    | '/auth'
    | '/cookie-policy'
    | '/dashboard'
    | '/privacy-legal'
    | '/tasks'
    | '/terms-of-service'
    | '/wallet'
    | '/task/$movieId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/account'
    | '/admin'
    | '/admin-secret-portal'
    | '/auth'
    | '/cookie-policy'
    | '/dashboard'
    | '/privacy-legal'
    | '/tasks'
    | '/terms-of-service'
    | '/wallet'
    | '/task/$movieId'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/account'
    | '/admin'
    | '/admin-secret-portal'
    | '/auth'
    | '/cookie-policy'
    | '/dashboard'
    | '/privacy-legal'
    | '/tasks'
    | '/terms-of-service'
    | '/wallet'
    | '/task/$movieId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AdminSecretPortalRoute: typeof AdminSecretPortalRoute
  AuthRoute: typeof AuthRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  DashboardRoute: typeof DashboardRoute
  PrivacyLegalRoute: typeof PrivacyLegalRoute
  TasksRoute: typeof TasksRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  WalletRoute: typeof WalletRoute
  TaskMovieIdRoute: typeof TaskMovieIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-legal': {
      id: '/privacy-legal'
      path: '/privacy-legal'
      fullPath: '/privacy-legal'
      preLoaderRoute: typeof PrivacyLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-secret-portal': {
      id: '/admin-secret-portal'
      path: '/admin-secret-portal'
      fullPath: '/admin-secret-portal'
      preLoaderRoute: typeof AdminSecretPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/$movieId': {
      id: '/task/$movieId'
      path: '/task/$movieId'
      fullPath: '/task/$movieId'
      preLoaderRoute: typeof TaskMovieIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AdminSecretPortalRoute: AdminSecretPortalRoute,
  AuthRoute: AuthRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  DashboardRoute: DashboardRoute,
  PrivacyLegalRoute: PrivacyLegalRoute,
  TasksRoute: TasksRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  WalletRoute: WalletRoute,
  TaskMovieIdRoute: TaskMovieIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
